// Code generated by MockGen. DO NOT EDIT.
// Source: code.mine/dating_server/repo (interfaces: Repo)

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	types "code.mine/dating_server/types"
	gomock "github.com/golang/mock/gomock"
	primitive "go.mongodb.org/mongo-driver/bson/primitive"
	options "go.mongodb.org/mongo-driver/mongo/options"
)

// MockRepo is a mock of Repo interface.
type MockRepo struct {
	ctrl     *gomock.Controller
	recorder *MockRepoMockRecorder
}

// MockRepoMockRecorder is the mock recorder for MockRepo.
type MockRepoMockRecorder struct {
	mock *MockRepo
}

// NewMockRepo creates a new mock instance.
func NewMockRepo(ctrl *gomock.Controller) *MockRepo {
	mock := &MockRepo{ctrl: ctrl}
	mock.recorder = &MockRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRepo) EXPECT() *MockRepoMockRecorder {
	return m.recorder
}

// GetUsersByFilter mocks base method.
func (m *MockRepo) GetUsersByFilter(arg0 *primitive.M, arg1 *options.FindOptions) ([]*types.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUsersByFilter", arg0, arg1)
	ret0, _ := ret[0].([]*types.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUsersByFilter indicates an expected call of GetUsersByFilter.
func (mr *MockRepoMockRecorder) GetUsersByFilter(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUsersByFilter", reflect.TypeOf((*MockRepo)(nil).GetUsersByFilter), arg0, arg1)
}

// GetVideosByAllUserUUIDs mocks base method.
func (m *MockRepo) GetVideosByAllUserUUIDs(arg0 []*string) ([]*types.UserVideoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideosByAllUserUUIDs", arg0)
	ret0, _ := ret[0].([]*types.UserVideoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideosByAllUserUUIDs indicates an expected call of GetVideosByAllUserUUIDs.
func (mr *MockRepoMockRecorder) GetVideosByAllUserUUIDs(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideosByAllUserUUIDs", reflect.TypeOf((*MockRepo)(nil).GetVideosByAllUserUUIDs), arg0)
}

// GetVideosByUserUUID mocks base method.
func (m *MockRepo) GetVideosByUserUUID(arg0 *string) ([]*types.UserVideoItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVideosByUserUUID", arg0)
	ret0, _ := ret[0].([]*types.UserVideoItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetVideosByUserUUID indicates an expected call of GetVideosByUserUUID.
func (mr *MockRepoMockRecorder) GetVideosByUserUUID(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVideosByUserUUID", reflect.TypeOf((*MockRepo)(nil).GetVideosByUserUUID), arg0)
}
